
FROM devlikeapro/waha:latest


ENV WAHA_API_KEY=${WAHA_API_KEY}
ENV WAHA_LOG_LEVEL=${WAHA_LOG_LEVEL}
ENV WAHA_DASHBOARD_USERNAME=${WAHA_DASHBOARD_USERNAME}
ENV WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD}


EXPOSE 3000

